### ISSUE TITLE
Weather Underground Icons

### ISSUE THREAD

**Issue by jlev** [johnotander/emojiweather#2]
The weather underground API includes conditions with a chance of occurring.
https://www.wunderground.com/weather/api/d/docs?d=resources/phrase-glossary#forecast_description_phrases

It might be nice to remove that phrase in your normalize function, so that even the possibility of rain results in 🌧.

Also, their phrase for ⛈ is "tstorms" not "tstorm"

**Comment by johno** [comment]
Thanks for opening the issue. Just pushed a new version `0.1.0` that handles `chance` phrases and is more wunderground friendly. Let me know if there's something still missing!
